### PR TITLE
A few benchmarking improvements.

### PR DESCRIPTION
**Pull request by dhess**
Add benchmarking support for Nix, and add a benchmark group for IPv6 from Text. (Currently only to Text is checked.)

### CODE REVIEW

**Comment by chessai** [comment]
benchmarking should be enabled already, no? If they aren't, i think you should use haskell.lib.doBench instead of passing "--benchmark" (i could be oblivious to a reason to do it this way)

**Comment by chessai** [comment]
Btw i do like the benchmark suite changes. Will merge if the nix issue is resolved (or im wrong and it's fine the way you have it)

**Comment by dhess** [comment]
Do you use Nix? If so, try it for yourself. The problem is that `callCabal2nix` doesn't call `configure` with `--enable-benchmark` unless you tell it to with explicit options, so when you try to run benchmarks in a Nix shell, even if you wrap it with `doBench`, it complains that the `criterion` dependency is missing.

**Comment by dhess** [comment]
Sorry, it appears you're right that wrapping the package with `doBenchmark` works as expected. I thought I'd tried that first and it didn't work, but I must have applied it to the wrong package. I'll fix this.

**Comment by chessai** [comment]
Yeah, I'd prefer doBenchmark

**Comment by chessai** [comment]
Thanks!

**Pull request merged**
