### PR TITLE
IPv6 ranges

### PR DESCRIPTION
**Pull request by goolord**
Implementation of IPv6 ranges

### CODE REVIEW

**Comment by andrewthad** [comment]
This is currently broken. I've added some tests.

**Comment by andrewthad** [comment]
I just added another test. This one checks that `succ . pred === id` and `pred . succ === id`. It currently fails for `IPv6` addresses. You'll probably need to run `cabal update` since this now requires a version of `quickcheck-classes` that was released this morning.

**Comment by goolord** [comment]
Everything should be good now.

**Comment by andrewthad** [comment]
This looks good. Merging.

**Pull request merged**
