### PR TITLE
Add Generic for IPv6

### PR DESCRIPTION
**Pull request by adamflott**

### CODE REVIEW

**Comment by adamflott** [comment]
Needed to derive Serialise from serialise package. Depends on a new wide-word package with https://github.com/erikd/wide-word/pull/51

**Comment by andrewthad** [comment]
This seems fine. When `wide-word` is released with the `Generic` instance, bump its lower bound in this PR and ping me, and then I can merge it.

**Comment by adamflott** [comment]
@andrewthad wide-word 0.1.1.2 was released with Generic instances. https://hackage.haskell.org/package/wide-word-0.1.1.2/changelog

Also, would you be opposed to getting this library into Stackage? (one of my favorites :)

**Comment by andrewthad** [comment]
This PR still needs to bump the lower bound on `wide-word`.

I'd be fine with getting this into stackage, but I'd like to address https://github.com/andrewthad/haskell-ip/issues/69 first since it is a considerable breaking change.

**Comment by andrewthad** [comment]
Also, needs a changelog entry.

**Comment by dbalan** [comment]
I need this :) @adamflott @andrewthad would you mind me finishing up this PR?

**Comment by adamflott** [comment]
@andrewthad updated changelog and lower bounds

**Pull request merged**
